- name: "restart nova-api"
  systemd: state=restarted daemon_reload=yes name=nova-api
- name: "restart nova-consoleauth"
  systemd: state=restarted daemon_reload=yes name=nova-consoleauth
- name: "restart nova-scheduler"
  systemd: state=restarted daemon_reload=yes name=nova-scheduler
- name: "restart nova-conductor"
  systemd: state=restarted daemon_reload=yes name=nova-conductor
- name: "restart nova-novncproxy"
  systemd: state=restarted daemon_reload=yes name=nova-novncproxy
