---
- name: mariadb - install
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - python-pymysql
    - python-mysqldb
  tags: mariadb_conf

- name: mariadb - configuration from template
  template:
    src: templates/99-openstack.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    owner: root
    group: root
    mode: 0600
  tags: mariadb_conf


- name: restart service mariadb
  systemd:
    state: restarted
    daemon_reload: yes
    name: mysql
  tags: mariadb_conf


- name: Set root Password
  mysql_user: 'login_password="{{ mysql_root_password }}" check_implicit_admin=yes name=root host="{{ item }}" password="{{ mysql_root_password }}" state=present'
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
  tags: mariadb_conf


- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
  tags: mariadb_conf


- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False
  tags: mariadb_conf


- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False
  tags: mariadb_conf


- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  tags: mariadb_conf


- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
  tags: mariadb_conf


- name: restart service mariadb
  systemd:
    state: restarted
    daemon_reload: yes
    name: mysql
  tags: mariadb_conf
